version: '3'
services:
  alist:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:9115"
    volumes:
      - "${CFG_PATH}:/config"
    environment:
      - "TZ=Asia/Shanghai"
      - "config.file=/config/blackbox.yml"
    image: prom/blackbox-exporter:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true